import type {
  ProductDataProvider,
  SourcedProduct,
  ProductSearchResult,
  ProductCategory,
} from "./index";

// ---------------------------------------------------------------------------
// Demo product catalog — 56 realistic products across 8 categories
// ---------------------------------------------------------------------------

function img(n: number): string {
  return `https://picsum.photos/400/400?random=${n}`;
}

function ship(hasFast = false): SourcedProduct["shippingOptions"] {
  const opts: SourcedProduct["shippingOptions"] = [
    { carrier: "AliExpress Standard Shipping", cost: 0, days: "15-25" },
  ];
  if (hasFast) {
    opts.push({ carrier: "ePacket", cost: 2.49, days: "10-18" });
  }
  return opts;
}

const PRODUCTS: SourcedProduct[] = [
  // ─── ELECTRONICS (8) ───────────────────────────────────────────────
  {
    externalId: "ele-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006100001.html",
    title: "TWS Wireless Bluetooth 5.3 Earbuds Active Noise Cancelling 30H Battery HiFi Stereo",
    description: "High-fidelity wireless earbuds with hybrid ANC, 30-hour total battery life, IPX5 waterproof. Touch controls, transparency mode, and low-latency game mode.",
    images: [img(101), img(102), img(103)],
    price: 8.99,
    originalPrice: 18.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 24850,
    category: "electronics",
    shippingOptions: ship(true),
    variants: [
      { id: "ele-001-v1", name: "Black", price: 8.99, stock: 5200, image: img(101) },
      { id: "ele-001-v2", name: "White", price: 8.99, stock: 3100, image: img(102) },
      { id: "ele-001-v3", name: "Blue", price: 9.49, stock: 1800, image: img(103) },
    ],
    isTrending: true,
  },
  {
    externalId: "ele-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006100002.html",
    title: "Shockproof Clear Phone Case MagSafe Compatible iPhone 15 14 13 Pro Max Slim Transparent",
    description: "Military-grade drop protection clear phone case with MagSafe ring, anti-yellowing material, raised edges for camera protection.",
    images: [img(104), img(105)],
    price: 2.49,
    originalPrice: 6.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 41200,
    category: "electronics",
    shippingOptions: ship(),
    variants: [
      { id: "ele-002-v1", name: "iPhone 15 Pro Max", price: 2.49, stock: 9800 },
      { id: "ele-002-v2", name: "iPhone 15 Pro", price: 2.49, stock: 7600 },
      { id: "ele-002-v3", name: "iPhone 14 Pro Max", price: 2.29, stock: 5400 },
    ],
    isTrending: true,
  },
  {
    externalId: "ele-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006100003.html",
    title: "65W GaN USB C Fast Charger PD3.0 QC4.0 Foldable Plug for MacBook iPhone Samsung",
    description: "Ultra-compact GaN III charger with foldable plug, dual USB-C + USB-A ports, intelligent power distribution.",
    images: [img(106), img(107)],
    price: 9.78,
    originalPrice: 24.99,
    currency: "USD",
    rating: 4.8,
    totalOrders: 18300,
    category: "electronics",
    shippingOptions: ship(true),
    variants: [
      { id: "ele-003-v1", name: "White - US Plug", price: 9.78, stock: 4200 },
      { id: "ele-003-v2", name: "Black - US Plug", price: 9.78, stock: 3100 },
      { id: "ele-003-v3", name: "White - EU Plug", price: 10.28, stock: 2800 },
    ],
    isTrending: true,
  },
  {
    externalId: "ele-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006100004.html",
    title: "USB C to Lightning Cable 2m MFi Certified Fast Charging Braided Nylon for iPhone",
    description: "Apple MFi certified USB-C to Lightning cable, braided nylon jacket, 20W fast charging support, 480Mbps data transfer.",
    images: [img(108)],
    price: 3.29,
    originalPrice: 8.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 32100,
    category: "electronics",
    shippingOptions: ship(),
    variants: [
      { id: "ele-004-v1", name: "1m - White", price: 2.89, stock: 8900 },
      { id: "ele-004-v2", name: "2m - White", price: 3.29, stock: 6200 },
      { id: "ele-004-v3", name: "2m - Black", price: 3.29, stock: 5100 },
    ],
    isTrending: true,
  },
  {
    externalId: "ele-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006100005.html",
    title: "Smart Watch 1.85\" HD Bluetooth Call Fitness Tracker Heart Rate SpO2 for Men Women",
    description: "Full touch 1.85-inch HD screen smartwatch with Bluetooth calling, 100+ sport modes, heart rate and blood oxygen monitoring, IP68 waterproof.",
    images: [img(109), img(110)],
    price: 11.99,
    originalPrice: 29.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 9400,
    category: "electronics",
    shippingOptions: ship(true),
    variants: [
      { id: "ele-005-v1", name: "Black Silicone", price: 11.99, stock: 3200 },
      { id: "ele-005-v2", name: "Silver Metal Band", price: 14.99, stock: 1800 },
    ],
    isNewArrival: true,
  },
  {
    externalId: "ele-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006100006.html",
    title: "RGB LED Strip Lights 5M/10M WiFi Smart App Control Music Sync for Room Decor",
    description: "WiFi RGB LED strip lights compatible with Alexa and Google Home, music sync, 16 million colors, cuttable, self-adhesive.",
    images: [img(111), img(112)],
    price: 5.49,
    originalPrice: 14.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 27600,
    category: "electronics",
    shippingOptions: ship(),
    variants: [
      { id: "ele-006-v1", name: "5m WiFi", price: 5.49, stock: 7800 },
      { id: "ele-006-v2", name: "10m WiFi", price: 8.99, stock: 4200 },
      { id: "ele-006-v3", name: "5m Bluetooth", price: 4.99, stock: 6100 },
    ],
    isTrending: true,
  },
  {
    externalId: "ele-007",
    sourceUrl: "https://www.aliexpress.com/item/1005006100007.html",
    title: '10" LED Ring Light with Tripod Stand & Phone Holder for TikTok YouTube Live Stream',
    description: "Professional ring light with 3 color modes, 10 brightness levels, 360-degree rotation, compatible with all smartphones.",
    images: [img(113), img(114)],
    price: 12.50,
    originalPrice: 28.00,
    currency: "USD",
    rating: 4.6,
    totalOrders: 15800,
    category: "electronics",
    shippingOptions: ship(true),
    variants: [
      { id: "ele-007-v1", name: '10"', price: 12.50, stock: 2400 },
      { id: "ele-007-v2", name: '12" + Remote', price: 16.80, stock: 1100 },
    ],
  },
  {
    externalId: "ele-008",
    sourceUrl: "https://www.aliexpress.com/item/1005006100008.html",
    title: "1080P Webcam with Microphone USB Plug and Play Auto Focus for Zoom Teams Meeting",
    description: "Full HD 1080P webcam with built-in noise-reducing mic, auto-focus, wide-angle lens, universal clip mount.",
    images: [img(115)],
    price: 7.99,
    originalPrice: 19.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 6200,
    category: "electronics",
    shippingOptions: ship(),
    variants: [
      { id: "ele-008-v1", name: "1080P Standard", price: 7.99, stock: 3800 },
      { id: "ele-008-v2", name: "2K with Light", price: 12.49, stock: 1200 },
    ],
    isNewArrival: true,
  },

  // ─── FASHION (7) ───────────────────────────────────────────────────
  {
    externalId: "fash-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006200001.html",
    title: "Polarized Sunglasses UV400 Men Women Classic Square Frame Driving Outdoor Sport",
    description: "Premium polarized lenses with TAC technology, lightweight TR90 frame, UV400 protection. Comes with case, cloth, and polarization test card.",
    images: [img(201), img(202)],
    price: 3.89,
    originalPrice: 12.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 19800,
    category: "fashion",
    shippingOptions: ship(),
    variants: [
      { id: "fash-001-v1", name: "Matte Black / Grey", price: 3.89, stock: 4500 },
      { id: "fash-001-v2", name: "Tortoise / Brown", price: 3.89, stock: 3200 },
      { id: "fash-001-v3", name: "Blue / Blue Mirror", price: 4.29, stock: 2100 },
    ],
    isTrending: true,
  },
  {
    externalId: "fash-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006200002.html",
    title: "Minimalist Layered Gold Necklace Set 18K Plated Stainless Steel Waterproof Jewelry Women",
    description: "Set of 3 layered necklaces in 18K gold plating on stainless steel. Hypoallergenic, tarnish-free, waterproof. Adjustable lengths.",
    images: [img(203), img(204)],
    price: 4.59,
    originalPrice: 14.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 28400,
    category: "fashion",
    shippingOptions: ship(true),
    variants: [
      { id: "fash-002-v1", name: "Gold 3-piece set", price: 4.59, stock: 6200 },
      { id: "fash-002-v2", name: "Silver 3-piece set", price: 4.59, stock: 4800 },
      { id: "fash-002-v3", name: "Rose Gold 3-piece", price: 4.99, stock: 3100 },
    ],
    isTrending: true,
  },
  {
    externalId: "fash-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006200003.html",
    title: "Quartz Watch Minimalist Ultra-Thin Mesh Band Stainless Steel Waterproof Unisex",
    description: "Japanese quartz movement, sapphire crystal glass, 316L stainless steel mesh band, 30M water resistant.",
    images: [img(205)],
    price: 6.99,
    originalPrice: 19.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 8900,
    category: "fashion",
    shippingOptions: ship(true),
    variants: [
      { id: "fash-003-v1", name: "Silver / White Dial", price: 6.99, stock: 2100 },
      { id: "fash-003-v2", name: "Gold / Black Dial", price: 7.49, stock: 1800 },
      { id: "fash-003-v3", name: "Rose Gold / Pink Dial", price: 7.49, stock: 1500 },
    ],
  },
  {
    externalId: "fash-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006200004.html",
    title: "Women Crossbody Bag PU Leather Small Shoulder Purse Chain Strap Flap Phone Bag",
    description: "Compact crossbody bag with detachable chain strap, card slots, magnetic flap closure. Fits phone up to 6.7 inches.",
    images: [img(206), img(207)],
    price: 5.89,
    originalPrice: 16.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 14200,
    category: "fashion",
    shippingOptions: ship(),
    variants: [
      { id: "fash-004-v1", name: "Black", price: 5.89, stock: 3400 },
      { id: "fash-004-v2", name: "Beige", price: 5.89, stock: 2800 },
      { id: "fash-004-v3", name: "Pink", price: 5.89, stock: 2200 },
    ],
  },
  {
    externalId: "fash-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006200005.html",
    title: "100% Mulberry Silk Hair Scrunchies Set of 6 Large Size Anti-Frizz Ponytail Holder",
    description: "Grade 6A mulberry silk scrunchies, gentle on hair, reduces frizz and breakage. Set of 6 assorted colors.",
    images: [img(208)],
    price: 3.49,
    originalPrice: 9.99,
    currency: "USD",
    rating: 4.8,
    totalOrders: 36700,
    category: "fashion",
    shippingOptions: ship(),
    variants: [
      { id: "fash-005-v1", name: "Neutral Set (6pc)", price: 3.49, stock: 8100 },
      { id: "fash-005-v2", name: "Pastel Set (6pc)", price: 3.49, stock: 5600 },
    ],
    isTrending: true,
  },
  {
    externalId: "fash-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006200006.html",
    title: "Cashmere Feel Scarf Women Winter Warm Shawl Wrap Oversized 200x70cm Solid Color",
    description: "Ultra-soft cashmere-feel acrylic scarf, oversized for versatile styling, fringe detail, lightweight yet warm.",
    images: [img(209)],
    price: 4.99,
    originalPrice: 14.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 5200,
    category: "fashion",
    shippingOptions: ship(),
    variants: [
      { id: "fash-006-v1", name: "Camel", price: 4.99, stock: 2400 },
      { id: "fash-006-v2", name: "Grey", price: 4.99, stock: 2100 },
      { id: "fash-006-v3", name: "Burgundy", price: 4.99, stock: 1900 },
    ],
    isNewArrival: true,
  },
  {
    externalId: "fash-007",
    sourceUrl: "https://www.aliexpress.com/item/1005006200007.html",
    title: "Genuine Leather Belt Men Automatic Buckle Ratchet Dress Belt Business Casual 35mm",
    description: "Full-grain cowhide leather belt with alloy automatic buckle, micro-adjustable ratchet system, no holes needed. Trimmable to fit.",
    images: [img(210)],
    price: 5.49,
    originalPrice: 15.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 11300,
    category: "fashion",
    shippingOptions: ship(),
    variants: [
      { id: "fash-007-v1", name: "Black / Silver Buckle", price: 5.49, stock: 3400 },
      { id: "fash-007-v2", name: "Brown / Gold Buckle", price: 5.49, stock: 2800 },
    ],
  },

  // ─── HOME & GARDEN (7) ────────────────────────────────────────────
  {
    externalId: "home-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006300001.html",
    title: "Vegetable Chopper 14-in-1 Mandoline Slicer Dicer Food Cutter with Container Kitchen",
    description: "Multi-function food chopper with 8 interchangeable blades, built-in colander, anti-slip base. BPA-free, dishwasher safe.",
    images: [img(301), img(302)],
    price: 7.89,
    originalPrice: 22.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 42100,
    category: "home",
    shippingOptions: ship(true),
    variants: [
      { id: "home-001-v1", name: "Green", price: 7.89, stock: 6400 },
      { id: "home-001-v2", name: "Blue", price: 7.89, stock: 4200 },
    ],
    isTrending: true,
  },
  {
    externalId: "home-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006300002.html",
    title: "Drawer Organizer Set 8-Pack Adjustable Dividers Storage Boxes for Underwear Socks Ties",
    description: "Set of 8 stackable drawer organizers in various sizes, fits standard drawers. Reinforced corners, washable fabric.",
    images: [img(303)],
    price: 4.99,
    originalPrice: 12.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 18900,
    category: "home",
    shippingOptions: ship(),
    variants: [
      { id: "home-002-v1", name: "Grey 8-pack", price: 4.99, stock: 5600 },
      { id: "home-002-v2", name: "Beige 8-pack", price: 4.99, stock: 3800 },
    ],
    isTrending: true,
  },
  {
    externalId: "home-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006300003.html",
    title: "Moon Lamp 3D Printed 16 Colors LED Night Light Remote Control Touch USB Rechargeable",
    description: "Realistic 3D moon surface texture, 16 color modes with remote, USB rechargeable, wooden stand included. Great gift idea.",
    images: [img(304), img(305)],
    price: 6.49,
    originalPrice: 18.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 31200,
    category: "home",
    shippingOptions: ship(true),
    variants: [
      { id: "home-003-v1", name: "10cm", price: 6.49, stock: 4200 },
      { id: "home-003-v2", name: "15cm", price: 9.99, stock: 2800 },
      { id: "home-003-v3", name: "20cm", price: 14.99, stock: 1200 },
    ],
    isTrending: true,
  },
  {
    externalId: "home-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006300004.html",
    title: "Bamboo Shower Caddy Corner Shelf 3-Tier Waterproof Bathroom Organizer Free Standing",
    description: "3-tier corner bamboo shelf, water-resistant coating, adjustable feet, no drilling required. Holds shampoo bottles and accessories.",
    images: [img(306)],
    price: 11.99,
    originalPrice: 29.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 7600,
    category: "home",
    shippingOptions: ship(),
    variants: [
      { id: "home-004-v1", name: "3-Tier Natural", price: 11.99, stock: 1800 },
      { id: "home-004-v2", name: "4-Tier Natural", price: 15.99, stock: 1200 },
    ],
  },
  {
    externalId: "home-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006300005.html",
    title: "Self-Watering Plant Pot Modern Minimalist with Drainage Wick System Indoor Planter",
    description: "Elegant self-watering planter with cotton wick system, removable inner pot, drainage hole. Perfect for herbs and succulents.",
    images: [img(307), img(308)],
    price: 3.29,
    originalPrice: 8.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 12400,
    category: "home",
    shippingOptions: ship(),
    variants: [
      { id: "home-005-v1", name: "Small White", price: 3.29, stock: 5100 },
      { id: "home-005-v2", name: "Medium White", price: 4.49, stock: 3600 },
      { id: "home-005-v3", name: "Small Black", price: 3.29, stock: 4200 },
    ],
  },
  {
    externalId: "home-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006300006.html",
    title: "Electric Milk Frother Handheld USB Rechargeable Mini Whisk Coffee Foam Maker 3-Speed",
    description: "Rechargeable milk frother with 3 speed settings, stainless steel whisk head, LED indicator. Creates rich foam in 15 seconds.",
    images: [img(309)],
    price: 4.49,
    originalPrice: 11.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 22300,
    category: "home",
    shippingOptions: ship(true),
    variants: [
      { id: "home-006-v1", name: "Black", price: 4.49, stock: 6800 },
      { id: "home-006-v2", name: "White", price: 4.49, stock: 4200 },
    ],
    isTrending: true,
  },
  {
    externalId: "home-007",
    sourceUrl: "https://www.aliexpress.com/item/1005006300007.html",
    title: "Magnetic Spice Rack Jars Set 12-Pack Stainless Steel with Labels for Refrigerator",
    description: "12 magnetic stainless steel spice jars with 120 pre-printed labels, strong magnets, clear lids. Sticks to fridge or metal surface.",
    images: [img(310)],
    price: 9.99,
    originalPrice: 24.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 3800,
    category: "home",
    shippingOptions: ship(),
    variants: [
      { id: "home-007-v1", name: "12-pack Silver", price: 9.99, stock: 2100 },
    ],
    isNewArrival: true,
  },

  // ─── BEAUTY & HEALTH (7) ──────────────────────────────────────────
  {
    externalId: "beau-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006400001.html",
    title: "Ice Roller Face Massager Stainless Steel Skin Care Tool Anti-Puffiness Dark Circles",
    description: "Stainless steel ice roller for face, reduces puffiness and dark circles, tightens pores. Store in freezer before use.",
    images: [img(401), img(402)],
    price: 2.79,
    originalPrice: 8.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 38400,
    category: "beauty",
    shippingOptions: ship(),
    variants: [
      { id: "beau-001-v1", name: "Silver", price: 2.79, stock: 9200 },
      { id: "beau-001-v2", name: "Rose Gold", price: 3.19, stock: 6400 },
    ],
    isTrending: true,
  },
  {
    externalId: "beau-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006400002.html",
    title: "Professional Makeup Brush Set 15-Piece Synthetic Kabuki Foundation Blending Eyeshadow",
    description: "15 premium synthetic brushes with wooden handles, vegan-friendly, includes foundation, powder, contour, blending, and eyeshadow brushes. PU leather case.",
    images: [img(403), img(404)],
    price: 5.99,
    originalPrice: 18.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 22100,
    category: "beauty",
    shippingOptions: ship(true),
    variants: [
      { id: "beau-002-v1", name: "Black 15-pc + Case", price: 5.99, stock: 4800 },
      { id: "beau-002-v2", name: "Pink 15-pc + Case", price: 5.99, stock: 3600 },
      { id: "beau-002-v3", name: "Black 10-pc Basic", price: 3.99, stock: 6200 },
    ],
    isTrending: true,
  },
  {
    externalId: "beau-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006400003.html",
    title: "Silk Satin Scrunchies Large Hair Ties Sleep Cap Combo Set Anti-Breakage Women",
    description: "Premium satin scrunchies 6-pack with matching sleep bonnet, reduces hair frizz and breakage. Gift box included.",
    images: [img(405)],
    price: 3.99,
    originalPrice: 11.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 15600,
    category: "beauty",
    shippingOptions: ship(),
    variants: [
      { id: "beau-003-v1", name: "Classic Colors 6-pc", price: 3.99, stock: 5400 },
      { id: "beau-003-v2", name: "Pastel Colors 6-pc", price: 3.99, stock: 4100 },
    ],
  },
  {
    externalId: "beau-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006400004.html",
    title: "Mini Massage Gun Portable Deep Tissue Percussion Muscle Massager USB-C 6 Heads",
    description: "Ultra-compact massage gun, 4 speed levels, 6 interchangeable heads, USB-C charging, brushless motor. Weighs only 350g.",
    images: [img(406), img(407)],
    price: 14.99,
    originalPrice: 39.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 11200,
    category: "beauty",
    shippingOptions: ship(true),
    variants: [
      { id: "beau-004-v1", name: "Grey", price: 14.99, stock: 2800 },
      { id: "beau-004-v2", name: "Pink", price: 14.99, stock: 2100 },
      { id: "beau-004-v3", name: "Black Pro (8 heads)", price: 18.99, stock: 1400 },
    ],
  },
  {
    externalId: "beau-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006400005.html",
    title: "Jade Gua Sha Stone Set Rose Quartz Face Sculpting Massage Tool Anti-Aging",
    description: "Genuine rose quartz gua sha and jade roller set in velvet pouch. Promotes circulation, reduces fine lines, lymphatic drainage.",
    images: [img(408)],
    price: 3.49,
    originalPrice: 12.99,
    currency: "USD",
    rating: 4.8,
    totalOrders: 29800,
    category: "beauty",
    shippingOptions: ship(),
    variants: [
      { id: "beau-005-v1", name: "Rose Quartz Set", price: 3.49, stock: 7200 },
      { id: "beau-005-v2", name: "Green Jade Set", price: 3.49, stock: 5400 },
    ],
    isTrending: true,
  },
  {
    externalId: "beau-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006400006.html",
    title: "Dermaplaning Tool Face Razor Eyebrow Shaper 12-Pack Japanese Steel Blade Women",
    description: "12 precision dermaplaning razors with safety guard, Japanese steel blades, removes peach fuzz and exfoliates.",
    images: [img(409)],
    price: 2.29,
    originalPrice: 7.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 46200,
    category: "beauty",
    shippingOptions: ship(),
    variants: [
      { id: "beau-006-v1", name: "12-pack Pink", price: 2.29, stock: 11200 },
      { id: "beau-006-v2", name: "12-pack White", price: 2.29, stock: 8400 },
    ],
    isTrending: true,
  },
  {
    externalId: "beau-007",
    sourceUrl: "https://www.aliexpress.com/item/1005006400007.html",
    title: "LED Teeth Whitening Kit Blue Light Gel Pen Professional Home Use 3 Gel Pens",
    description: "LED blue light teeth whitening device with 3 gel pens, 16-minute timer, USB rechargeable. Removes years of stains.",
    images: [img(410)],
    price: 6.99,
    originalPrice: 19.99,
    currency: "USD",
    rating: 4.2,
    totalOrders: 4100,
    category: "beauty",
    shippingOptions: ship(),
    variants: [
      { id: "beau-007-v1", name: "Standard Kit (3 gels)", price: 6.99, stock: 2800 },
      { id: "beau-007-v2", name: "Pro Kit (6 gels)", price: 9.99, stock: 1400 },
    ],
    isNewArrival: true,
  },

  // ─── SPORTS & OUTDOORS (7) ────────────────────────────────────────
  {
    externalId: "sport-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006500001.html",
    title: "Non-Slip Yoga Mat 6mm TPE Eco-Friendly Alignment Lines Home Gym Fitness Exercise",
    description: "Premium TPE yoga mat with alignment guide lines, dual-texture non-slip surface, lightweight 800g, includes carry strap.",
    images: [img(501), img(502)],
    price: 8.49,
    originalPrice: 22.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 19400,
    category: "sports",
    shippingOptions: ship(true),
    variants: [
      { id: "sport-001-v1", name: "Purple / Pink", price: 8.49, stock: 3600 },
      { id: "sport-001-v2", name: "Blue / Grey", price: 8.49, stock: 2800 },
      { id: "sport-001-v3", name: "Black / Grey", price: 8.49, stock: 2400 },
    ],
    isTrending: true,
  },
  {
    externalId: "sport-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006500002.html",
    title: "Resistance Bands Set 5-Pack Latex Loops Exercise Bands with Carry Bag Workout Guide",
    description: "5 resistance levels (5-40lbs), natural latex, non-snap technology, includes mesh carry bag and exercise guide.",
    images: [img(503)],
    price: 3.29,
    originalPrice: 9.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 48200,
    category: "sports",
    shippingOptions: ship(),
    variants: [
      { id: "sport-002-v1", name: "5-Band Set", price: 3.29, stock: 12400 },
      { id: "sport-002-v2", name: "5-Band + Handles", price: 5.99, stock: 6200 },
    ],
    isTrending: true,
  },
  {
    externalId: "sport-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006500003.html",
    title: "Insulated Water Bottle 750ml Stainless Steel Vacuum Flask Keep Cold 24H Hot 12H BPA Free",
    description: "Double-wall vacuum insulation, 18/8 stainless steel, sweat-free exterior, wide mouth, powder-coated finish.",
    images: [img(504), img(505)],
    price: 5.99,
    originalPrice: 16.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 21600,
    category: "sports",
    shippingOptions: ship(true),
    variants: [
      { id: "sport-003-v1", name: "500ml Black", price: 4.99, stock: 5200 },
      { id: "sport-003-v2", name: "750ml Black", price: 5.99, stock: 3800 },
      { id: "sport-003-v3", name: "750ml White", price: 5.99, stock: 3100 },
    ],
    isTrending: true,
  },
  {
    externalId: "sport-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006500004.html",
    title: "Ultralight Camping Hammock Portable Parachute Nylon Double Person with Tree Straps",
    description: "300x200cm double hammock, holds 300kg, parachute nylon, includes 2 tree straps and carabiners. Packs into attached pouch.",
    images: [img(506)],
    price: 7.99,
    originalPrice: 21.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 8700,
    category: "sports",
    shippingOptions: ship(true),
    variants: [
      { id: "sport-004-v1", name: "Army Green / Black", price: 7.99, stock: 2100 },
      { id: "sport-004-v2", name: "Blue / Grey", price: 7.99, stock: 1800 },
      { id: "sport-004-v3", name: "Rainbow", price: 8.49, stock: 1200 },
    ],
  },
  {
    externalId: "sport-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006500005.html",
    title: "Gym Gloves Men Women Half Finger Weight Lifting Crossfit Anti-Slip Palm Padding",
    description: "Breathable mesh back, anti-slip silicone palm padding, adjustable wrist wrap, pull tab for easy removal.",
    images: [img(507)],
    price: 3.79,
    originalPrice: 10.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 7200,
    category: "sports",
    shippingOptions: ship(),
    variants: [
      { id: "sport-005-v1", name: "Black M", price: 3.79, stock: 3200 },
      { id: "sport-005-v2", name: "Black L", price: 3.79, stock: 2800 },
      { id: "sport-005-v3", name: "Black XL", price: 3.79, stock: 2400 },
    ],
  },
  {
    externalId: "sport-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006500006.html",
    title: "Jump Rope Speed Skipping Rope Weighted Ball Bearing Handle Crossfit MMA Boxing",
    description: "Ball bearing swivel handles, adjustable 3m steel cable, ergonomic anti-slip grips, suitable for double-unders.",
    images: [img(508)],
    price: 2.99,
    originalPrice: 8.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 14300,
    category: "sports",
    shippingOptions: ship(),
    variants: [
      { id: "sport-006-v1", name: "Black", price: 2.99, stock: 6200 },
      { id: "sport-006-v2", name: "Red", price: 2.99, stock: 3800 },
    ],
  },
  {
    externalId: "sport-007",
    sourceUrl: "https://www.aliexpress.com/item/1005006500007.html",
    title: "Headlamp Rechargeable LED 1000 Lumens IPX4 Waterproof 5 Modes Camping Running Hiking",
    description: "USB-C rechargeable headlamp, 1000 lumens max, red light mode, motion sensor, adjustable beam angle. 8-hour runtime.",
    images: [img(509)],
    price: 4.49,
    originalPrice: 12.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 5800,
    category: "sports",
    shippingOptions: ship(true),
    variants: [
      { id: "sport-007-v1", name: "Black", price: 4.49, stock: 3200 },
      { id: "sport-007-v2", name: "Orange", price: 4.49, stock: 2100 },
    ],
    isNewArrival: true,
  },

  // ─── TOYS & HOBBIES (6) ───────────────────────────────────────────
  {
    externalId: "toy-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006600001.html",
    title: "Pop Fidget Toys Push Bubble Sensory Pack Stress Relief Anxiety Kids Adults 10-Pack",
    description: "Set of 10 assorted fidget toys including pop-its, mesh tubes, infinity cubes, and spinners. Non-toxic silicone.",
    images: [img(601), img(602)],
    price: 4.29,
    originalPrice: 12.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 33400,
    category: "toys",
    shippingOptions: ship(),
    variants: [
      { id: "toy-001-v1", name: "10-Pack Assorted", price: 4.29, stock: 8400 },
      { id: "toy-001-v2", name: "20-Pack Mega", price: 7.99, stock: 4200 },
    ],
    isTrending: true,
  },
  {
    externalId: "toy-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006600002.html",
    title: "RC Car 4WD Off-Road Monster Truck 2.4GHz Remote Control 1:16 Scale High Speed 30km/h",
    description: "All-terrain RC truck with rubber tires, independent suspension, rechargeable 1200mAh battery, 25-minute runtime.",
    images: [img(603), img(604)],
    price: 15.99,
    originalPrice: 39.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 6800,
    category: "toys",
    shippingOptions: ship(true),
    variants: [
      { id: "toy-002-v1", name: "Blue", price: 15.99, stock: 1800 },
      { id: "toy-002-v2", name: "Red", price: 15.99, stock: 1400 },
    ],
  },
  {
    externalId: "toy-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006600003.html",
    title: "3D Wooden Puzzle Mechanical Model DIY Assembly Kit Clock Marble Run STEM Toy",
    description: "Laser-cut wooden 3D puzzle with 250+ pieces, no glue required, functioning gear mechanism. Great STEM educational toy.",
    images: [img(605)],
    price: 9.99,
    originalPrice: 24.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 14200,
    category: "toys",
    shippingOptions: ship(true),
    variants: [
      { id: "toy-003-v1", name: "Clock Tower", price: 9.99, stock: 2400 },
      { id: "toy-003-v2", name: "Marble Run", price: 12.99, stock: 1800 },
      { id: "toy-003-v3", name: "Music Box", price: 8.99, stock: 2800 },
    ],
    isTrending: true,
  },
  {
    externalId: "toy-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006600004.html",
    title: "Acrylic Paint Set 24 Colors Non-Toxic Art Supplies with 10 Brushes Canvas for Beginners",
    description: "24 vibrant acrylic paint tubes (12ml each), 10 brushes, 3 mini canvases, mixing palette. Perfect starter set.",
    images: [img(606)],
    price: 6.49,
    originalPrice: 17.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 9200,
    category: "toys",
    shippingOptions: ship(),
    variants: [
      { id: "toy-004-v1", name: "24-Color + Brushes", price: 6.49, stock: 3600 },
      { id: "toy-004-v2", name: "36-Color Pro Set", price: 9.99, stock: 2100 },
    ],
  },
  {
    externalId: "toy-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006600005.html",
    title: "Magnetic Building Blocks Tiles 100-Piece Set STEM Construction Toy Children 3+",
    description: "100 magnetic tiles in assorted shapes and colors, strong magnets, ABS plastic. Compatible with major brands.",
    images: [img(607), img(608)],
    price: 12.99,
    originalPrice: 34.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 16800,
    category: "toys",
    shippingOptions: ship(true),
    variants: [
      { id: "toy-005-v1", name: "100-piece", price: 12.99, stock: 3200 },
      { id: "toy-005-v2", name: "60-piece", price: 8.99, stock: 4800 },
    ],
    isTrending: true,
  },
  {
    externalId: "toy-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006600006.html",
    title: "Diamond Painting Kit 5D DIY Full Drill Round Crystal Rhinestone Landscape Wall Art",
    description: "Full-drill 5D diamond painting kit with pre-printed canvas, sorted DMC color beads, pen, wax, and tray.",
    images: [img(609)],
    price: 4.79,
    originalPrice: 13.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 3400,
    category: "toys",
    shippingOptions: ship(),
    variants: [
      { id: "toy-006-v1", name: '30x40cm Sunset', price: 4.79, stock: 2800 },
      { id: "toy-006-v2", name: '40x50cm Mountain', price: 6.99, stock: 1800 },
    ],
    isNewArrival: true,
  },

  // ─── PETS (6) ──────────────────────────────────────────────────────
  {
    externalId: "pet-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006700001.html",
    title: "Interactive Cat Toy Feather Wand Retractable Teaser Rod 5 Replacement Heads",
    description: "Retractable feather wand toy with 5 interchangeable heads (feathers, bells, fish), telescopic rod 37-96cm.",
    images: [img(701), img(702)],
    price: 2.49,
    originalPrice: 7.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 25300,
    category: "pets",
    shippingOptions: ship(),
    variants: [
      { id: "pet-001-v1", name: "5-Head Set", price: 2.49, stock: 8200 },
      { id: "pet-001-v2", name: "10-Head Mega Set", price: 3.99, stock: 4600 },
    ],
    isTrending: true,
  },
  {
    externalId: "pet-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006700002.html",
    title: "Pet Grooming Glove Deshedding Brush Gentle Hair Remover Massage Tool Dogs Cats",
    description: "Silicone grooming glove with 259 tips, works on wet/dry fur, adjustable wrist strap. Collect loose fur effortlessly.",
    images: [img(703)],
    price: 2.29,
    originalPrice: 6.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 31200,
    category: "pets",
    shippingOptions: ship(),
    variants: [
      { id: "pet-002-v1", name: "Right Hand Blue", price: 2.29, stock: 7400 },
      { id: "pet-002-v2", name: "Right Hand Pink", price: 2.29, stock: 5200 },
      { id: "pet-002-v3", name: "Pair (L+R) Blue", price: 3.99, stock: 3100 },
    ],
    isTrending: true,
  },
  {
    externalId: "pet-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006700003.html",
    title: "Reflective Dog Collar Adjustable Nylon Padded Quick Release Buckle S/M/L/XL",
    description: "Reflective nylon collar with neoprene padding, quick-release buckle, D-ring for leash. Available in 4 sizes.",
    images: [img(704)],
    price: 2.89,
    originalPrice: 7.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 14600,
    category: "pets",
    shippingOptions: ship(),
    variants: [
      { id: "pet-003-v1", name: "S Red", price: 2.49, stock: 3200 },
      { id: "pet-003-v2", name: "M Blue", price: 2.89, stock: 4100 },
      { id: "pet-003-v3", name: "L Black", price: 3.29, stock: 2800 },
    ],
  },
  {
    externalId: "pet-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006700004.html",
    title: "Orthopedic Dog Bed Memory Foam Washable Cover Non-Slip Bottom Medium Large Dogs",
    description: "Egg-crate memory foam mattress, removable machine-washable cover, anti-slip rubber bottom. Joint and hip support.",
    images: [img(705), img(706)],
    price: 14.99,
    originalPrice: 39.99,
    currency: "USD",
    rating: 4.7,
    totalOrders: 8400,
    category: "pets",
    shippingOptions: ship(true),
    variants: [
      { id: "pet-004-v1", name: "Medium Grey", price: 14.99, stock: 1800 },
      { id: "pet-004-v2", name: "Large Grey", price: 19.99, stock: 1200 },
    ],
  },
  {
    externalId: "pet-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006700005.html",
    title: "Automatic Pet Water Fountain 2L Filter Cat Dog Drinking Dispenser Ultra Quiet USB",
    description: "2L automatic water fountain with triple filtration, ultra-quiet pump (<30dB), LED indicator. Encourages pets to drink more.",
    images: [img(707)],
    price: 8.99,
    originalPrice: 22.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 12100,
    category: "pets",
    shippingOptions: ship(true),
    variants: [
      { id: "pet-005-v1", name: "White 2L", price: 8.99, stock: 3400 },
      { id: "pet-005-v2", name: "Blue 2L + 4 Filters", price: 11.49, stock: 2100 },
    ],
  },
  {
    externalId: "pet-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006700006.html",
    title: "Dog Rope Toys Indestructible 6-Pack Cotton Knot Chew Toys Teeth Cleaning Small Medium",
    description: "6 durable cotton rope toys, non-toxic dyes, helps clean teeth and massage gums. Assorted shapes and sizes.",
    images: [img(708)],
    price: 3.49,
    originalPrice: 9.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 4200,
    category: "pets",
    shippingOptions: ship(),
    variants: [
      { id: "pet-006-v1", name: "6-pack Small/Medium", price: 3.49, stock: 4800 },
      { id: "pet-006-v2", name: "4-pack Large", price: 4.49, stock: 2800 },
    ],
    isNewArrival: true,
  },

  // ─── AUTO (6) ──────────────────────────────────────────────────────
  {
    externalId: "auto-001",
    sourceUrl: "https://www.aliexpress.com/item/1005006800001.html",
    title: "Car Phone Holder Mount Dashboard Air Vent Windshield Universal 360 Rotation Strong Suction",
    description: "3-in-1 phone mount for dashboard, air vent, or windshield. Strong suction cup, 360-degree rotation, one-hand operation.",
    images: [img(801), img(802)],
    price: 3.49,
    originalPrice: 9.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 28700,
    category: "auto",
    shippingOptions: ship(),
    variants: [
      { id: "auto-001-v1", name: "Suction Cup Black", price: 3.49, stock: 6800 },
      { id: "auto-001-v2", name: "Air Vent Clip Black", price: 3.29, stock: 5200 },
    ],
    isTrending: true,
  },
  {
    externalId: "auto-002",
    sourceUrl: "https://www.aliexpress.com/item/1005006800002.html",
    title: "Car Seat Gap Filler Organizer PU Leather Console Side Pocket Storage Box 2-Pack",
    description: "Fills the gap between seat and console, PU leather surface, holds phone, wallet, keys. Prevents items from falling. Set of 2.",
    images: [img(803)],
    price: 4.99,
    originalPrice: 13.99,
    currency: "USD",
    rating: 4.4,
    totalOrders: 19400,
    category: "auto",
    shippingOptions: ship(),
    variants: [
      { id: "auto-002-v1", name: "Black 2-pack", price: 4.99, stock: 5400 },
      { id: "auto-002-v2", name: "Brown 2-pack", price: 4.99, stock: 3200 },
    ],
    isTrending: true,
  },
  {
    externalId: "auto-003",
    sourceUrl: "https://www.aliexpress.com/item/1005006800003.html",
    title: "Trunk Organizer Collapsible Car Storage Box Multi-Compartment Waterproof Oxford Fabric",
    description: "Foldable trunk organizer with 3 compartments, reinforced bottom, side pockets, carry handles. Folds flat when not in use.",
    images: [img(804)],
    price: 7.99,
    originalPrice: 19.99,
    currency: "USD",
    rating: 4.6,
    totalOrders: 11800,
    category: "auto",
    shippingOptions: ship(true),
    variants: [
      { id: "auto-003-v1", name: "Black Standard", price: 7.99, stock: 3200 },
      { id: "auto-003-v2", name: "Black with Cooler", price: 10.99, stock: 1800 },
    ],
  },
  {
    externalId: "auto-004",
    sourceUrl: "https://www.aliexpress.com/item/1005006800004.html",
    title: "Car Vacuum Cleaner Portable 9000PA Cordless Handheld USB-C Rechargeable Mini",
    description: "9000PA powerful suction, cordless handheld design, HEPA filter, USB-C charging, 30-minute runtime. Includes crevice tool.",
    images: [img(805), img(806)],
    price: 12.49,
    originalPrice: 32.99,
    currency: "USD",
    rating: 4.3,
    totalOrders: 7600,
    category: "auto",
    shippingOptions: ship(true),
    variants: [
      { id: "auto-004-v1", name: "White", price: 12.49, stock: 2100 },
      { id: "auto-004-v2", name: "Black", price: 12.49, stock: 1800 },
    ],
  },
  {
    externalId: "auto-005",
    sourceUrl: "https://www.aliexpress.com/item/1005006800005.html",
    title: "LED Car Interior Ambient Light Strip APP Control 64 Colors Music Sync 4-in-1 Fiber Optic",
    description: "4 fiber optic light strips with app control, 64 colors, music sync, adjustable brightness. Easy plug-in installation.",
    images: [img(807)],
    price: 8.99,
    originalPrice: 24.99,
    currency: "USD",
    rating: 4.5,
    totalOrders: 15200,
    category: "auto",
    shippingOptions: ship(true),
    variants: [
      { id: "auto-005-v1", name: "4-strip Bluetooth", price: 8.99, stock: 3600 },
      { id: "auto-005-v2", name: "6-strip App Control", price: 12.99, stock: 2200 },
    ],
    isTrending: true,
  },
  {
    externalId: "auto-006",
    sourceUrl: "https://www.aliexpress.com/item/1005006800006.html",
    title: "Blind Spot Mirror 360 Degree Adjustable Wide Angle HD Glass Car Side Mirror 2-Pack",
    description: "Frameless convex blind spot mirrors, adjustable 360-degree swivel, HD glass, strong 3M adhesive. Easy install.",
    images: [img(808)],
    price: 2.19,
    originalPrice: 6.99,
    currency: "USD",
    rating: 4.2,
    totalOrders: 2900,
    category: "auto",
    shippingOptions: ship(),
    variants: [
      { id: "auto-006-v1", name: "Round 2-pack", price: 2.19, stock: 6400 },
      { id: "auto-006-v2", name: "Fan-shape 2-pack", price: 2.49, stock: 4200 },
    ],
    isNewArrival: true,
  },
];

// ---------------------------------------------------------------------------
// Category meta
// ---------------------------------------------------------------------------
const CATEGORY_MAP: Record<string, string> = {
  electronics: "Electronics",
  fashion: "Fashion",
  home: "Home & Garden",
  beauty: "Beauty & Health",
  sports: "Sports & Outdoors",
  toys: "Toys & Hobbies",
  pets: "Pets",
  auto: "Auto",
};

const PAGE_SIZE = 12;

// ---------------------------------------------------------------------------
// DemoProvider implementation
// ---------------------------------------------------------------------------
export class DemoProvider implements ProductDataProvider {
  async searchProducts(
    query: string,
    page = 1,
    category?: string,
  ): Promise<ProductSearchResult> {
    const q = query.toLowerCase();
    let filtered = PRODUCTS.filter((p) => {
      const matchesQuery =
        !q ||
        p.title.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q) ||
        p.category.toLowerCase().includes(q);
      const matchesCategory = !category || category === "all" || p.category === category;
      return matchesQuery && matchesCategory;
    });

    const total = filtered.length;
    const start = (page - 1) * PAGE_SIZE;
    filtered = filtered.slice(start, start + PAGE_SIZE);

    return { products: filtered, total, page, pageSize: PAGE_SIZE };
  }

  async getProductDetails(productId: string): Promise<SourcedProduct | null> {
    return PRODUCTS.find((p) => p.externalId === productId) ?? null;
  }

  async getTrendingProducts(
    category?: string,
    page = 1,
  ): Promise<ProductSearchResult> {
    let trending = PRODUCTS.filter((p) => {
      const matchesCat = !category || category === "all" || p.category === category;
      return matchesCat && (p.isTrending || p.totalOrders > 15000);
    }).sort((a, b) => b.totalOrders - a.totalOrders);

    const total = trending.length;
    const start = (page - 1) * PAGE_SIZE;
    trending = trending.slice(start, start + PAGE_SIZE);

    return { products: trending, total, page, pageSize: PAGE_SIZE };
  }

  async getCategories(): Promise<{ id: string; name: string; count: number }[]> {
    const counts: Record<string, number> = {};
    for (const p of PRODUCTS) {
      counts[p.category] = (counts[p.category] ?? 0) + 1;
    }
    return Object.entries(counts).map(([id, count]) => ({
      id,
      name: CATEGORY_MAP[id] ?? id,
      count,
    }));
  }
}
